#!/usr/bin/python

import sys
import argparse
import ipaddress
import socket

ap = argparse.ArgumentParser()
ap.add_argument("ip", nargs=1, help="IPv4 or IPv6 address")
ap.add_argument("rbls", nargs="+", help="RBLs to check")
args = ap.parse_args()

bls = args.rbls
ip = args.ip[0]

listed = 0
for bl in bls:
    addr = ipaddress.ip_address(ip)
    if isinstance(addr, ipaddress.IPv6Address):
        ipv6 = addr.exploded
        rev = '.'.join(reversed(ipv6.replace(":", "")))
    if isinstance(addr, ipaddress.IPv4Address):
        ipv4 = addr.exploded
        rev = '.'.join(reversed(ipv4.split(".")))

    blhost = rev + "." + bl
    try:
        ret = socket.getaddrinfo(blhost, 0)
        print(ret[0][4][0])
        listed = 1
    except socket.gaierror:
        print("not listed")

sys.exit(listed)
